### DISCUSSION TITLE
Persisting Postgres Data

### DISCUSSION THREAD

**Discussion by jaysonng** [netreconlab/parse-server-swift#59] [Ideas]
I've been moving my data from Mongo to Postgres and testing around. 

I found out that with the current default Postgres setup in docker-compose.yml that data won't persist when `docker-compose down` is run. 

Is there any reason that isn't an option yet (no commented out lines like other options in the docker-compose file).

I found that adding volumes fixes that. 

```yml
  db:
    image: netreconlab/hipaa-postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_PARSE_USER: ${PG_PARSE_USER}
      PG_PARSE_PASSWORD: ${PG_PARSE_PASSWORD}
      PG_PARSE_DB: ${PG_PARSE_DB}
      PMM_USER: ${PMM_USER}
      PMM_PASSWORD: ${PMM_PASSWORD}
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
```

If there's a better setup for it pls do let me know.
